create table if not exists booking_clean (
  id bigint generated by default as identity primary key,
  booking_ref text,
  booking_party text,
  origin_port text,
  load_port text,
  discharge_port text,
  final_port text,
  country text,
  freight numeric,
  vessel_voyage text,
  transhipment text,
  container_type text,
  teus numeric,
  units numeric,
  service_voyage text,
  source_file text,
  uploaded_at timestamp default now()
);

create table if not exists booking_container_clean (
  id bigint generated by default as identity primary key,
  booking_ref text,
  booking_party text,
  origin_port text,
  load_port text,
  discharge_port text,
  final_port text,
  country text,
  freight numeric,
  vessel_voyage text,
  transhipment text,
  container_no text,
  container_type text,
  teus numeric,
  units numeric,
  service_voyage text,
  source_file text,
  uploaded_at timestamp default now()
);

create table if not exists operational_payload (
  id bigint generated by default as identity primary key,
  source_file text,
  source_sheet text,
  operation text,
  dataset text,
  operation_table text,
  payload jsonb,
  uploaded_at timestamp default now()
);

create index if not exists idx_booking_clean_booking_ref
  on booking_clean (booking_ref);

create index if not exists idx_booking_container_clean_container_no
  on booking_container_clean (container_no);

create index if not exists idx_operational_payload_operation
  on operational_payload (operation);

create index if not exists idx_operational_payload_dataset
  on operational_payload (dataset);

create index if not exists idx_operational_payload_container_json
  on operational_payload ((coalesce(payload->>'container_id', payload->>'container_no')));

